import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa";
import {
  SiDjango,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGooglechat,
  SiGraphql,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiJson,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiNotion,
  SiNginx,
  SiOdoo,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiReact,
  SiRedis,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiWebcomponentsdotorg,
  SiXml,
} from "react-icons/si";
import { TbBrandOpenai } from "react-icons/tb";

export const skillIconMap: Record<string, IconType> = {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiOpenjdk,
  SiPhp,
  SiXml,
  SiJson,
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiOdoo,
  SiWebcomponentsdotorg,
  SiFlutter,
  SiTensorflow,
  SiPytorch,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  FaAws,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiJenkins,
  SiLinux,
  TbBrandOpenai,
  SiFigma,
  SiTailwindcss,
  SiGooglechat,
  SiJira,
  SiNotion,
  SiGraphql,
  SiFirebase,
  SiNginx,
};
